In [2]:
!pip install requests

Requirement already satisfied: requests in C:\Users\impra\anaconda3\Lib\site-packages (2.34.2)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\impra\anaconda3\Lib\site-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\impra\anaconda3\Lib\site-packages (from requests) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\impra\anaconda3\Lib\site-packages (from requests) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\impra\anaconda3\Lib\site-packages (from requests) (2026.7.22)

In [3]:
import requests

In [33]:
URL = "https://stephen-king-api.onrender.com/api/books"
res=requests.get(URL)

In [34]:
res

In [35]:
json_data=res.json()

In [36]:
json_data
print(res.headers.get("Content-Type"))

application/json; charset=utf-8

In [37]:
import pandas as pd

In [19]:
df=pd.json_normalize(json_data["data"])

In [20]:
df

,id,Year,Title,handle,Publisher,ISBN,Pages,Notes,created_at,villains
0,1,1974,Carrie,carrie,Doubleday,978-0-385-08695-0,199,[],2023-11-13T23:48:47.848Z,"[{'name': 'Tina Blake', 'url': 'https://stephe..."
1,2,1975,Salem's Lot,salem-s-lot,Doubleday,978-0-385-00751-1,439,"[Nominee, World Fantasy Award, 1976[2]]",2023-11-13T23:48:48.098Z,"[{'name': 'Kurt Barlow', 'url': 'https://steph..."
2,3,1977,The Shining,the-shining,Doubleday,978-0-385-12167-5,447,"[Runner-up (4th place), Locus Award for Best F...",2023-11-13T23:48:48.219Z,"[{'name': 'Horace M. Derwent', 'url': 'https:/..."
3,4,1977,Rage,rage,Signet Books,978-0-451-07645-8,211,[Published under pseudonym Richard Bachman],2023-11-13T23:48:48.339Z,[]
4,5,1978,The Stand,the-stand,Doubleday,978-0-385-12168-2,823,"[Nominee, World Fantasy Award, 1979, Runner-up...",2023-11-13T23:48:48.477Z,"[{'name': 'Donald Merwin Elbert', 'url': 'http..."
...,...,...,...,...,...,...,...,...,...,...
59,60,2018,Elevation,elevation,Scribner,978-1-98210-231-9,144,[],2023-11-13T23:48:55.291Z,[]
60,61,2019,The Institute,the-institute,Scribner,978-1-98211-056-7,576,"[Nominee, British Fantasy Award's August Derle...",2023-11-13T23:48:55.457Z,"[{'name': 'Gladys Hickson', 'url': 'https://st..."
61,62,2021,Later,later,Hard Case Crime,978-1-78909-649-1,256,[],2023-11-13T23:48:55.579Z,[]
62,63,2021,Billy Summers,billy-summers,Scribner,978-1-982-17361-6,528,[],2023-11-13T23:48:55.753Z,[]
63,72,1979,The Roopak Zone,the-roopak-zone,Viking Press,978-0-670-26069697-5,428,"[Runner-up (2nd place), Locus Award for Best F...",2026-06-26T18:20:32.285Z,[]

In [21]:
df=df[["id","Title", "Year", "ISBN"]]

In [22]:
df

    id            Title  Year                  ISBN
0    1           Carrie  1974     978-0-385-08695-0
1    2      Salem's Lot  1975     978-0-385-00751-1
2    3      The Shining  1977     978-0-385-12167-5
3    4             Rage  1977     978-0-451-07645-8
4    5        The Stand  1978     978-0-385-12168-2
..  ..              ...   ...                   ...
59  60        Elevation  2018     978-1-98210-231-9
60  61    The Institute  2019     978-1-98211-056-7
61  62            Later  2021     978-1-78909-649-1
62  63    Billy Summers  2021     978-1-982-17361-6
63  72  The Roopak Zone  1979  978-0-670-26069697-5

[64 rows x 4 columns]

In [23]:
# homeWork.........

In [52]:
import requests

In [56]:
url="https://api.ukhsa-dashboard.data.gov.uk/themes/infectious_disease/sub_themes/respiratory/topics/COVID-19/geography_types/Nation/geographies/England/metrics/COVID-19_cases_casesByDay"
responce=requests.get(url)

In [57]:
responce

In [66]:
print(responce.headers.get("content-Type"))

application/json

In [67]:
json_data=responce.json()

In [68]:
json_data

{'count': 2436,
 'next': 'https://api.ukhsa-dashboard.data.gov.uk/themes/infectious_disease/sub_themes/respiratory/topics/COVID-19/geography_types/Nation/geographies/England/metrics/COVID-19_cases_casesByDay?page=2',
 'previous': None,
 'results': [{'theme': 'infectious_disease',
   'sub_theme': 'respiratory',
   'topic': 'COVID-19',
   'geography_type': 'Nation',
   'geography': 'England',
   'geography_code': 'E92000001',
   'metric': 'COVID-19_cases_casesByDay',
   'metric_group': 'cases',
   'stratum': 'default',
   'sex': 'all',
   'age': 'all',
   'year': 2020,
   'month': 1,
   'epiweek': 5,
   'date': '2020-01-30',
   'metric_value': 1.0,
   'in_reporting_delay_period': False},
  {'theme': 'infectious_disease',
   'sub_theme': 'respiratory',
   'topic': 'COVID-19',
   'geography_type': 'Nation',
   'geography': 'England',
   'geography_code': 'E92000001',
   'metric': 'COVID-19_cases_casesByDay',
   'metric_group': 'cases',
   'stratum': 'default',
   'sex': 'all',
   'age': 'all',
   'year': 2020,
   'month': 1,
   'epiweek': 5,
   'date': '2020-01-31',
   'metric_value': 0.0,
   'in_reporting_delay_period': False},
  {'theme': 'infectious_disease',
   'sub_theme': 'respiratory',
   'topic': 'COVID-19',
   'geography_type': 'Nation',
   'geography': 'England',
   'geography_code': 'E92000001',
   'metric': 'COVID-19_cases_casesByDay',
   'metric_group': 'cases',
   'stratum': 'default',
   'sex': 'all',
   'age': 'all',
   'year': 2020,
   'month': 2,
   'epiweek': 5,
   'date': '2020-02-01',
   'metric_value': 0.0,
   'in_reporting_delay_period': False},
  {'theme': 'infectious_disease',
   'sub_theme': 'respiratory',
   'topic': 'COVID-19',
   'geography_type': 'Nation',
   'geography': 'England',
   'geography_code': 'E92000001',
   'metric': 'COVID-19_cases_casesByDay',
   'metric_group': 'cases',
   'stratum': 'default',
   'sex': 'all',
   'age': 'all',
   'year': 2020,
   'month': 2,
   'epiweek': 5,
   'date': '2020-02-02',
   'metric_value': 1.0,
   'in_reporting_delay_period': False},
  {'theme': 'infectious_disease',
   'sub_theme': 'respiratory',
   'topic': 'COVID-19',
   'geography_type': 'Nation',
   'geography': 'England',
   'geography_code': 'E92000001',
   'metric': 'COVID-19_cases_casesByDay',
   'metric_group': 'cases',
   'stratum': 'default',
   'sex': 'all',
   'age': 'all',
   'year': 2020,
   'month': 2,
   'epiweek': 6,
   'date': '2020-02-03',
   'metric_value': 18.0,
   'in_reporting_delay_period': False}]}

In [69]:
import pandas as pd

In [74]:
df1=pd.json_normalize(json_data)

In [78]:
df1=df1["count"]

In [79]:
df1

0    2436
Name: count, dtype: int64